### PR TITLE
Removing init.deployement.php from repo

### PR DESCRIPTION
**Pull request by lgnap**
Without that any modification of the file ask for a git commit.

Ansible doesn't allow to redeploy an already modified repo. So I need to remove it totally  from repo.

It's rewrited using ansible.

For the other commit it's an classic issue. It's a fatal on php 7.1

### CODE REVIEW

**Comment by Quix0r** [comment]
Oh, your commits went out with an other email address than registered here.

You can fix this in 2 ways:
- recommit both commits with fixed email address and don't forget to use `--reset-author`
- register that new email address here so it becomes linked to your account

And I like the idea of having it being ignored by git as it may contain sensitive data.

**Comment by Quix0r** [comment]
Or: rename it to init.deployment.php-dist which contains only example data. Very common.

**Comment by lgnap** [comment]
I rewrite commits with my new public email address declared on github.

Thanks for the notice

**Comment by ekinhbayar** [comment]
These changes were done in #75 and #84, hence I'm closing this PR, thanks!

**Comment by Quix0r** [comment]
@lgnap you're welcome.

**Pull request closed without merging**
