### PR TITLE
Updated unit tests to latest PHPUnit 6.2

### PR DESCRIPTION
**Pull request by Quix0r**
This PR updates all unit tests to latest PHPUnit 6.2.

### CODE REVIEW

**Comment by ekinhbayar** [comment]
Closing as this was done in #87, thanks!

**Comment by PeeHaa** [comment]
Sorry it took me this long and let your PR rot like that to the point it was easier to merge the other one instead :-(

FWIW I am very thankful for your contribution anyway!

**Comment by Quix0r** [comment]
Okay, has the issue then being fixed?

**Comment by PeeHaa** [comment]
yes. Master runs on 7+ including the tests

**Pull request closed without merging**
